media:
  input: src/images
  output: /images
  label: Images
content:
  - name: paintings
    label: Paintings
    type: collection
    path: 'src/paintings'
    view:
      fields: [ title, image, date, featured, available, tags ]
    fields:
      - name: available
        label: Available?
        type: boolean
        default: true
      - name: featured
        label: Featured on homepage?
        type: boolean
        default: false
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: tags
        label: Category
        type: select
        options:
          values:
            - value: paintings
              label: Painting
            - value: digital
              label: Digital
            - value: dry-media
              label: Dry Media
            - value: sketches
              label: Sketch
  - name: site
    label: Site settings
    path: src/_data/website.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
  - name: about
    label: About
    path: src/about.md
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: contact
    label: Contact
    path: src/contact.md
    type: file
    fields:
      - name: title
        label: Page title
        type: string
      - name: body
        label: Body
        type: rich-text